name: Build webpack

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install Next.js
        run: npm install next --save

      - name: Install project dependencies
        run: npm install

      - name: Build project
        run: npm run build
